Results for each assessment and domain are listed on the left-hand side of this page. You can access your complete results at `r daacs.base.url`, or click on any domain for more detailed feedback. Below are some resources and tips that can help you be more prepared for college.


### `r colorize("Self-Regulated Learning", "54075B")`

* See the last page of this document for specific tips you can start using right away.
* For more tips visit the Self-Regulated Learning Lab: [srl.daacs.net](https://srl.daacs.net)

### `r colorize("Writing", "54075B")`

* Visit the Online Writing Lab for tips on improving your writing skills: [owl.excelsior.edu](https://owl.excelsior.edu)
* Schedule an appointment at the Writing Center to receive help with your writing.

### `r colorize("Mathematics", "54075B")`

* Review the questions you answered incorrectly [on the DAACS website](https://assessment.albany.edu), and read the explanations for the correct answers by clicking "More Info" for each question within DAACS.
* There are several free websites that can help you with your math skills, such as [mathantics.com](https://mathantics.com), [mathsisfun.com](https://mathsisfun.com), and [virtualnerd.com](https://virtualnerd.com)
* If math is an area of concern and importance for you, consider scheduling an appointment with a tutor.


### `r colorize("Reading", "54075B")`

* Review the questions you answered incorrectly [on the DAACS website](https://assessment.albany.edu), and read the explanations for the correct answers by clicking "More Info" for each question within DAACS.
* Visit the Online Reading Lab for tips on improving your reading skills: [owl.excelsior.edu/orc](https://owl.excelsior.edu/orc)
* View the resources that are available at your library.
* Consider scheduling an appointment with a tutor.
